### ISSUE TITLE
Should EasyMock throw an Exception if a method is called while in Record state?

### ISSUE THREAD

**Issue by BloodChiefStromberg** [easymock/easymock#244]
EasyMock doesn't throw an exception if a mocked method is invoked while still in record state. It simply returns null for that method. If the mocked method is called too many times, however, it does throw an exception. IE if you have `expect(mock.someMethod()).andReturn("not null").times(1)`, and you call `mock.someMethod()` before calling `replay(mock)`, it will return `null`. If you call it again, it throws an exception. 

Is there a reason it doesn't throw an exception on the first invocation? Why is the current behavior desireable? 

Thanks for the great framework!

**Comment by henri-tremblay** [comment]
Yes. There is a reason. It's the way calls are recorded.

Doing `expect(mock.someMethod()).andReturn("not null")` is the same as doing 

```
mock.someMethod();
expect(null).andReturn("not null");
```

So I can't throw an exception from `someMethod()` because I have no idea if `expect` will be called or not. When it is called again, I can say: "Hey! There was something already recorded but not your calling some other method but there was no `expect` in the middle". It's the same thing when replay is called.
