### ISSUE TITLE
Mock annotation produces incompatible return value type

### ISSUE THREAD

**Issue by kobebryant2007** [easymock/easymock#265]
Hi all,
Recently, I uplift easymock from 3.4 to 4.2 and then, an issue appeared with the code below(all code runs on JDK8):

```
@PrepareForTest({ Method.class })
public class DemoTest {
    @Test
    public void demoTest() {
        IMock mock = EasyMock.createMock(IMock.class);
        Test testAnno = EasyMock.createMock(Test.class);
        Method method = PowerMock.createMock(Method.class);

        EasyMock.expect(mock.test()).andReturn(method).anyTimes();
        EasyMock.expect(method.getAnnotation(Test.class)).andReturn(testAnno).anyTimes();
        PowerMock.replay(method);
    }
}
```

the interface is like:
```
public interface IMock {
    Method test();
}
```

the testng, easymock powermock version is:
```
        <powermock-module-testng.version>2.0.9</powermock-module-testng.version>
        <powermock-api-easymock.version>2.0.9</powermock-api-easymock.version>
        <easymock.version>4.2</easymock.version>
       <testng.version>7.3.0</testng.version>
```

and after running the test case, it would produce an error message:
```
java.lang.IllegalStateException: incompatible return value type

	at org.easymock.internal.MocksControl.andReturn(MocksControl.java:281)
```

**Comment by henri-tremblay** [comment]
Thanks for the good report. I was able to reproduce. However, it is not an EasyMock bug. Your problem comes from PowerMock. The call to `method.getAnnotation(Test.class)` is a real call, not a mocked call. I'm not sure why. I'm not a PowerMock expert. What I do know if that I had issues with mocking JDK classes before using PowerMock. You will need to ask them to find a solution.

**Comment by kobebryant2007** [comment]
Thanks a lot for your suggestion, I'll create ticket for powermock.
